/**
 * IMAGE BLUR PLACEHOLDERS FOR NEXT/IMAGE
 * Automatically generated by scripts/optimize-images.mjs
 */

export const IMAGE_BLURS: Record<string, string> = {
  "slayt-1": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoUAAsAPzmGulOvKSWisAgB4CcJYwC/OBe9wJqd60TrRwAA/gEedri/cMZppHBkyXvpmmAL5N5lSr/AamkAKYL1myJVA1PZJH3UHau0ZOLfFFMDtXqCxF4IAAA=",
  "slayt-2": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZAAAN9uirYvqdYf2/HAA/pGTKhZOVMU2CcpwKbBcXgeMExGLF6WgZNrtf/Qc+TAPjtFtlRBDhjQeeXlc9wsAMCBEy8OGS1iJvLlNuMmQ4NJRXXtBTxJ5xgAAAA==",
  "slayt-3": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJQBUegVhqNWHFtAAA/d5Tg4puO9/mhfWM5axgxhqQyAKSFopLkvqvgisqNFPe5FRKkAF57AXlf0RgZV+Hf4D3zkZOtS6zu44AAA==",
  "sub-banner": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJQBhmhH5MS8Z23/dQAv/AAP7APyzw0bI2MWyGUkxLmHF1XqYlEO2qY8v2GZg3Tf7thN34HIBmy7ooAAA=",
  "kirsehir-nakliyat-faaliyet-1": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQBACdASoUABsAPzmGvFavKCYjsBgIAeAnCWIAwcwFa9Oo9jdVLcQw/g/bRXJ4bADZIX1yK0heH2W8WUYff7XiRjP5IkWOk8stSeIG1BRg7HJE2O6YlB3fUWoUeOEqC48vasDoXKQC16YmmqarpxuBAz4ouUSAAAA=",
  "kirsehir-nakliyat-faaliyet-2": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQBACdASoUABsAPzmMvFQvKiYjMAgB4CcJQBdgBDoisj5gi0bTSkWJF4grfPtcAAD+ixTX2/JEIVcSk3uW+yOeUN0su7e6UDlwzapcmM2MALCXO+ngQWYY49ijD4gl6a7S+IaAEHZgoAAA",
  "kirsehir-nakliyat-faaliyet-3": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBACdASoUABsAPzmAt1UvJyUjMBgMAeAnCWUAxzApa7hLxdOYeXM5fuV4AACo/M0+N4T4K8KgEUGUM5YLDeacdesoNlwFqUWtdMBcKYYFgqSHZDg32DSEm4k5Ry0TD6r6VHdcsjKLGgce8PWToOvzAvgAAA==",
  "kirsehir-nakliyat-faaliyet-4": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoUAA4APzmEuVOvKKWisAgB4CcJbACw7AvRrkILtuBgAMlcv/4Xo5eMBaIPP/CpHSMR/PZ6o8sqFQ6TNdQEObEwIebl+tGpuL+Xt1ttksDEV/sdEuLDqAAA",
  "kirsehir-nakliyat-faaliyet-5": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAA8APzmEuVOvKKWisAgB4CcJagCdABk4LCFtCFaGCAAA3lcdV6xCZcKk0zuB5SLAfyG3k2x2GN67urfDxttoXuOGV7zBvFxATGdU4u7yQAAA",
  "kirsehir-nakliyat-faaliyet-6": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBQCdASoUABsAPzmMu1WvKaYjMBgIAeAnCWQAnTMvxPQKDNAQoILJmQRjeVz3X9zDgAD+sKr6kshtetCYImEbHhJTFgNwK59xi+OvjxKMBLUJOxQRAOw5YB4AOa/X76c/PKP7P3A5Y/FGUAz+hwQZ2SEdYa0dwiDR1wEV3K19DkhlWLL1fAAA",
  "kirsehir-nakliyat-faaliyet-7": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZQAAVFfUB8QPk9R8DgDLKCEzrhYkpeXxIvVZI0rzqyyWEyPEDGaVObSW4LZI9z3rS/mlVCXi2rtX306YMmmKt/o4AA=="
};
